# Generated by Django 4.0 on 2021-12-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('user_posted', models.CharField(default='admin', max_length=64, verbose_name='Пользователь')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=512, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('-is_active', '-date'),
            },
        ),
    ]
